import type { Metadata } from 'next';
import localFont from 'next/font/local';

import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const aa = '';

  return (
    <html lang="en">
      {children != null ? (
        <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
      ) : aa == '' ? (
        <span>a</span>
      ) : (
        <span>b</span>
      )}
    </html>
  );
}
